=== Techie499/Guide-for-Beginners/XML/booklist.dtd
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE booklist[
<!ELEMENT booklist (books) >
<!ELEMENT book (title,author,price,qty) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA) >
<!ELEMENT price(#PCDATA) >
<!ELEMENT qty (#PCDATA) >
<!ATTLIST book pid type "softcopy">

=== Techie499/Guide-for-Beginners/XML08.07/external.xml
<?xml-stylesheet href="newstyle.css" type="text/css"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">
<booklist>
<book pid="b012" type="softcopy">
<title>Certificate programm in Web Designing</title>
<author>Phoenix Computer Training</author>
<price>250</price>
<qty>50</qty>
</book>
<book pid="b015" type="softcopy">
<title>Certificate programm in Web Develeopment</title>
<author>Phoenix Computer Training</author>
<price>250</price>
<qty>50</qty>
</book>
</booklist>
