<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet href="docStyle.css" type="text/css"?>
<!DOCTYPE details [
<!ELEMENT details (student+,name,fname,lname,code,course,validity+,day,month,year,mobile,email)>
<!ELEMENT student (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT validity (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>
<details>
<student gender="male">
	<name>
		<fname>Tathagata</fname>
		<lname>Banerjee</lname>
	</name>
	<code>2015-9637</code>
	<course>Web Designing</course>
	<validity id="sdate">
		<day>02</day>
		<month>06</month>
		<year>2019</year>
	</validity>
	<validity id="enddate">
		<day>16</day>
		<month>08</month>
		<year>2019</year>
	</validity>
	<mobile>9674253641</mobile>
	<email>tathagata@gmail.com</email>
</student>
<student gender="female">
	<name>
		<fname>Sayani </fname>
		<lname>Das</lname>
	</name>
	<code>2015-9599</code>
	<course>PhP and MySQL</course>
	<validity id="sdate">
		<day>02</day>
		<month>06</month>
		<year>2019</year>
	</validity>
	<validity id="enddate">
		<day>16</day>
		<month>08</month>
		<year>2019</year>
	</validity>
	<mobile>9674253641</mobile>
	<email>tathagata@gmail.com</email>
</student>
</details>